twittersite/twitter/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView



urlpatterns = [
    url(r'^$', views.TweetListView.as_view(), name="tweetlist"),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(), name="profiledetail"),
    url(r'^myfeed/$', login_required(views.MyFeedView.as_view()), name="myfeed"),
    url(r'^profile/(?P<pk>\d+)/addpost/$', login_required(views.CreatePost.as_view()), name="createpost"),
    url(r'^profile/(?P<pk>\d+)/posts/$', login_required(views.UserPosts.as_view()), name="userposts"),
    url(r'^profile/(?P<pk>\d+)/follow/$', login_required(views.FollowFormView.as_view()), name="follow"),
    url(r'^profile/(?P<pk>\d+)/follow/success/$', login_required(views.FollowSuccessView.as_view()), name="followsuccess"),
    url(r'^profile/(?P<pk>\d+)/update', login_required(views.UpdateProfile.as_view()), name="updateprofile"),

] 

twittersite/twittersite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('twitter.urls', namespace='twitter')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twittersite/twitter/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User)
    bio = models.TextField('Short Bio',blank=True, null=True)
    picture = models.ImageField(upload_to="pics/%Y/%m/%d", blank=True, null=True)
    following = models.ManyToManyField('self', blank=True, symmetrical=False)

    def __unicode__(self):
        return self.user.get_full_name() or self.user.username

class Post(models.Model):
    profile = models.ForeignKey(Profile)
    body = models.CharField(max_length=140)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-pub_date",)

    def __unicode__(self):
        return self.body

twittersite/twitter/forms.py
from django import forms

class PostForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea, max_length=140)
    user = forms.HiddenInput()

twittersite/twitter/views.py
from django.shortcuts import render
from .models import Profile, Post
from .forms import PostForm
from django.views.generic import ListView, UpdateView, CreateView, TemplateView, DetailView, FormView
from django.views.generic.detail import View, SingleObjectMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django import forms
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

# Create your views here.

#homework:
# do list view of all recent posts, profile detail view,

class TweetListView(ListView):
    model = Post
    paginate_by = 5 #need to add pagination code
    queryset = Post.objects.all().order_by('-pub_date')



#class CreatePost(CreateView):
#    model = Post
#    fields = ['body']


#    def get_success_url(self):
#        return reverse('twitter:userposts', args=self.args)

class CreatePost(FormView):
    template_name = 'twitter/post_form.html'
    form_class = PostForm

    def form_valid(self, form):
        post = Post()
        post.body = form.cleaned_data['body']
        post.profile = Profile.objects.get(pk=self.kwargs['pk'])
        post.save()
        return super(CreatePost, self).form_valid(form)


    def get_success_url(self):
        return reverse('twitter:userposts', args = (self.kwargs['pk'],))


class ProfileDetailView(DetailView):
    model = Profile


class UserPosts(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(profile = self.kwargs['pk'])



class MyFeedView(ListView):
    model = Post
    paginate_by = 10
    template_name = "twitter/myfeed.html"

    def get_queryset(self):
        my_profile = Profile.objects.get_or_create(user=self.request.user)
        my_profile = self.request.user.profile_set.all()[0]
        profile_list = list(my_profile.following.all())
        profile_list.append(my_profile)
        return Post.objects.filter(profile__in = profile_list)



class UpdateProfile(UpdateView):
    model = Profile
    fields = ['picture', 'bio']

    def get_success_url(self):
        return reverse('twitter:profiledetail', args=(self.kwargs['pk'],))



class FollowFormView(SingleObjectMixin, View):
    model = Profile

    def post(self, request, *args, **kwargs):
        my_profile = request.user.profile_set.all()[0]
        try:
            my_profile.following.add(self.kwargs['pk'])
            my_profile.save()
        except:
            return HttpResponseRedirect(reverse('twitter:followsuccess', args= (self.kwargs['pk'], )))
        #return HttpResponseRedirect(reverse('microblog:followsuccess', kwargs = {'pk': self.get_object().pk}))
        #if request.is_ajax():
        #    return Http
        return HttpResponseRedirect(reverse('twitter:followsuccess', args = (self.kwargs['pk'], )))

class FollowSuccessView(DetailView):
    template_name = 'twitter/follow_success.html'
    model = Profile

twittersite/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{% block title %} Starter Template for Bootstrap {% endblock %}</title>

    <!-- Bootstrap core CSS -->

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!--<script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  {% block extrascripts %}{% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">TwitterClone</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              {% if request.user.is_authenticated %}
                  <li><a href="/myfeed">MyFeed</a></li>
                  <li><a href="{% url 'twitter:profiledetail' request.user.profile_set.all.0.id %}">MyProfile</a></li>
                  <li><a href="{% url 'twitter:userposts' request.user.profile_set.all.0.id %}">MyPosts</a></li>
              <li><a href="/accounts/logout">Log Out</a></li>

              {% else %}
              <li><a href="/accounts/login">Log In</a></li>
                  <li><a href="/accounts/register">Sign Up</a></li>
              {% endif %}



          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container" style="margin-top: 75px;">
{% block content %}
      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
{% endblock %}

    {% if is_paginated %}
    <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'twitter:tweetlist' %}?page={{ page_obj.previous_page_number }}"> &lt;Prev </a>
                {% endif %}
                <span class="page-current">
                    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'twitter:tweetlist' %}?page={{ page_obj.next_page_number }}"> Next&gt; </a>
                {% endif %}
            </span>
        </div>
{% endif %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!--<script src="../../dist/js/bootstrap.min.js"></script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>
</html>

twittersite/templates/base3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

      <title>{% block title %} Starter Template for Bootstrap {% endblock %}</title>

    <title>Cover Template for Bootstrap</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extrascripts %}{% endblock %}
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Cover</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">Features</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
              {% block content %}
            <h1 class="cover-heading">Cover your page.</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-default">Learn more</a>
            </p>
              {% endblock %}
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

twittersite/twitter/templates/twitter/_feed.html
{%  load thumbnail %}

    {% for post in post_list %}
        <div {% ifequal post.profile.user request.user %} class="mark"{% endifequal %}>
        <p style="font-size: large">
        {% ifnotequal post.profile.user request.user %}
        {% if post.profile.picture %}

            {% thumbnail post.profile.picture "100x100" crop="center" as im %}
            <img src="{{ im.url }}" style="text-align: center;">
        {% endthumbnail %}
        {% else %}
            <img src="/media/no-profile-image.jpg" width="100" height="100" style="text-align: center;">
        {% endif %}
        {% endifnotequal %}



             {{ post.body }}
        </p>
        <h5><a href="{% url 'twitter:profiledetail' post.profile.id %}"> {{ post.profile.user}} </a> ({{ post.pub_date|date:"M d, Y h:m" }})</h5>
        </div>
        <hr>



    {% empty %}
    <p>No tweets submitted yet. </p>

    {% endfor %}

twittersite/twitter/templates/twitter/_post.html
{%  load thumbnail %}

    {% for post in profile.post_set.all|slice:":10" %}
        <p>

             {{ post.body }}
        </p>
        <h5 style="text-align: right;">{{ post.pub_date|date:"M d, Y h:m" }}</h5>
        <hr>


    {% empty %}
    <p>No current posts. </p>
        {% if profile.user == request.user %}
        <p>Want to <a href="">make one?</a></p>
        {% endif %}

    {% endfor %}

twittersite/twitter/templates/twitter/follow_success.html
{% extends 'base.html' %}

{% block title %} Success{% endblock %}

{% block content %}

    You've successfully followed <a href="{% url 'twitter:profiledetail' profile.id %}"> @{{ profile.user.username }} </a>.

{% endblock %}

twittersite/twitter/templates/twitter/myfeed.html
{% extends 'base.html' %}

{% block title %} @{{ request.user }}'s Feed {% endblock %}

{% block content %}
    <h2>My Feed</h2>
    <br>
    <br>
    {% include 'twitter/_feed.html' %}




{% endblock %}

twittersite/twitter/templates/twitter/post_form.html
{% extends 'base.html' %}

{% block title %} Add Post (@{{ request.user }}) {% endblock %}

{% block content %}
    <h2>New Post</h2>

        <form method="post">
        {% csrf_token %}
        <table class="table">
        {{ form }}
        <td><button type="submit" class="btn btn-default" name="submit">Add Post</button></td>
            <td><a href="{% url 'twitter:profiledetail' request.user.profile_set.all.0.id %}" class="btn btn-default">Cancel</a></td>
        </table>
    </form>


{% endblock %}

twittersite/twitter/templates/twitter/post_list.html
{% extends 'base.html' %}

{% block title %} Twitter Knock Off{% endblock %}

{% block content %}

    <h2> TwitterClone Posts</h2>
    <br>
    <br>

    {% include 'twitter/_feed.html' %}



{% endblock %}

twittersite/twitter/templates/twitter/profile_detail.html
{% extends 'base.html' %}

{% block title %} @{{ profile.user.username }}'s Profile {% endblock %}

{% block content %}

    <h1> @{{ profile.user.username }}</h1>

    {%  load thumbnail %}
    {% if profile.picture %}
        {% thumbnail profile.picture "300x300" crop="center" as im %}
        <img src="{{ im.url }}" style="text-align: center;">
        {% endthumbnail %}
    {% else %}
        <img src="/media/no-profile-image.jpg" width="300" height="300" style="text-align: center;">
    {% endif %}

    {% if request.user != profile.user %}

    <div class="followbutton btn">
        <form action="{% url 'twitter:follow' profile.id %}" method="post">
            {% csrf_token %}
            <button class="btn btn-default" type="submit">Follow @{{ profile.user.username }}</button>
        </form>
    </div>
    {% else %}
        <a style="margin-left:15px;" class="btn btn-default" href="{% url 'twitter:updateprofile' profile.id %}" >Update My Profile</a> <br>
    {% endif %}

    <h2>Bio </h2>


    <div class="well" style="margin-top:15px;">


        {% if profile.bio != "" %}
        {{ profile.bio }}
        {% else %}
            @{{profile.user.username}} hasn't done anything interesting... that we know about.
            {% if profile.user == request.user %}
            <a href="{% url 'twitter:updateprofile' profile.id %}">Update Your Bio</a>
                {% else %}
                Tell him to update his bio!
            {% endif %}
        {% endif %}
    </div>
    <h2> Following </h2>
    <ul>
        {% for p in profile.following.all %}
            <li><a href="{% url 'twitter:profiledetail' p.id %}">@{{ p.user }}</a></li>
     {% endfor %}
    </ul>

    <h2> <a href="{% url 'twitter:userposts' profile.id %}">Recent Posts</a> </h2>
    <a href="{% url 'twitter:createpost' profile.id %}" class="btn btn-default"> Add Post</a>
    <hr>

    {% include 'twitter/_post.html' %}


{% endblock %}

twittersite/twitter/templates/twitter/profile_form.html
{% extends 'base.html' %}

{% block title %} Update @{{ profile.user.username }}'s Profile {% endblock %}

{% block content %}
    <h2>Update @{{ profile.user }}'s Profile</h2>
    {%  load thumbnail %}
    {% if profile.picture %}
        {% thumbnail profile.picture "300x300" crop="center" as im %}
        <img src="{{ im.url }}" style="text-align: center;">
        {% endthumbnail %}
    {% else %}
        <img src="/media/no-profile-image.jpg" width="300" height="300" style="text-align: center;">
    {% endif %}

        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
        {{ form.as_p }}
        <td colspan="2"><button type="submit" name="submit">Update Profile</button></td>
        </table>

    </form>


{% endblock %}