suggestionbox/kaizen/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^$', login_required(views.IdeaListView.as_view()), name="idealist"),
    url(r'^(?P<pk>[0-9]+)/status/$', login_required(views.ChangeStatusView.as_view()), name="changestatus"),
    url(r'^newidea/$', login_required(views.CreateIdeaView.as_view()), name="newidea"),
    url(r'^category/$', login_required(views.CategoryListView.as_view()), name="categorylist"),
    url(r'^category/(?P<pk>[0-9]+)/$', login_required(views.CategoryDetailView.as_view()), name="categorydetail" ),
    url(r'^category/new/$', login_required(views.CreateCategory.as_view()), name="createcategory"),
    url(r'^idea/(?P<pk>[0-9]+)/$', views.IdeaDetailView.as_view(), name="ideadetail"),
    url(r'^comment/(?P<pk>[0-9]+)/$', views.CommentForm.as_view(), name="addcomment"),
]

suggestionbox/suggestionbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('kaizen.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),

]

suggestionbox/kaizen/models.py
from django.db import models
from django.contrib.auth.models import User
from userena.models import UserenaBaseProfile

STATUS = {
    ('new', 'New'),
    ('den', 'Denied'),
    ('rev', 'In Review'),
    ('2do', 'To Do'),
    ('imp', 'Implemented'),
}

# Create your models here.
class Profile(UserenaBaseProfile):
    user = models.ForeignKey(User)
    is_admin = models.BooleanField(default=False)

    def __unicode__(self):
        return self.user.get_full_name() or self.user.username


class Category(models.Model):
    title = models.CharField(max_length=200)

    def __unicode__(self):
        return self.title


class Idea(models.Model):
    profile = models.ForeignKey(Profile)
    title = models.CharField(max_length=200)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=3, choices=STATUS, default='new')
    category = models.ForeignKey(Category) #would have to be in qutoes if declared BEFORE category was defined

    def __unicode__(self):
        return self.title

class Comment(models.Model):
    comment_text = models.TextField()
    idea = models.ForeignKey(Idea)
    profile = models.ForeignKey(Profile)
    pub_date = models.DateTimeField(auto_now_add=True)

suggestionbox/kaizen/views.py
from django.shortcuts import render
from .models import Idea, Profile, Category, Comment
from django.views.generic import ListView, UpdateView, CreateView, TemplateView, DetailView, FormView
from django.core.urlresolvers import reverse


# Create your views here.
class IdeaListView(ListView):
    model = Idea

class IdeaDetailView(DetailView):
    model = Idea


class ChangeStatusView(UpdateView):
    model = Idea
    fields = ['status']
    template_name = "kaizen/changestatus.html"

    def get_success_url(self):
        return reverse('ideadetail', args=(self.object.pk,))

class CreateIdeaView(CreateView):
    model = Idea
    fields = ['title','description','category']

    def form_valid(self, form):
        idea = form.save(commit=False)

        #print self.__dict__
        idea.profile = Profile.objects.filter(user = self.request.user)[0]
        idea.save()
        return super(CreateIdeaView, self).form_valid(form)

    def get_success_url(self):
        return reverse('ideadetail', args=(self.object.pk,))


class CategoryListView(ListView):
    model = Category

class CategoryDetailView(DetailView):
    model = Category

class CreateCategory(CreateView):
    model = Category
    fields = ['title']

    def get_success_url(self):
        return reverse('categorydetail', args=(self.object.pk,))


class CommentForm(CreateView):
    model = Comment
    fields = ['comment_text', 'idea']

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.profile = Profile.objects.filter(user = self.request.user)[0]
        comment.save()
        return super(CommentForm, self).form_valid(form)


    def get_success_url(self):
        return reverse('ideadetail', args=(self.object.idea.id,))

suggestionbox/kaizen/templates/kaizen/category_detail.html
{% extends 'base.html' %}

{% block 'title' %} Kaizen Categories{% endblock %}

{% block 'content' %}

    <h1>Category: {{ category.title }}</h1>

    {% for idea in category.idea_set.all %}
        <h3><a href="{% url 'ideadetail' idea.id %}">{{ idea.title }}</a></h3>

    {% empty %}
    <p>No Kaizens exist for this category yet. Want to <a href="{% url 'newidea' %}">submit one?</a></p>
    {% endfor %}
    <br>
    <br>
    <a href="{% url 'idealist' %}">View All Kaizens</a>
    <br>
    


{% endblock %}

suggestionbox/kaizen/templates/kaizen/category_form.html
{% extends 'base.html' %}

{% block 'title' %} New Kaizens Category{% endblock %}

{% block 'content' %}


    <form action="." method="post">
        {% csrf_token %}
        <table class="table">
        {{ form }}
        <td colspan="2"><button type="submit" id="submit" name="submit">Add a new category!</button></td>
        </table>

    </form>



{% endblock %}

suggestionbox/kaizen/templates/kaizen/category_list.html
{% extends 'base.html' %}

{% block 'title' %} Kaizen Categories{% endblock %}

{% block 'content' %}

    <h1>Kaizens Categories</h1>
    <a href="{% url 'idealist' %}">View All Kaizens</a>
    {% for category in category_list %}
        <h3><a href="{% url 'categorydetail' category.id %}">{{ category.title }}</a></h3>

    {% empty %}
    <p>No categories exist yet. Want to <a href="{% url 'createcategory' %}">add one?</a></p>
    {% endfor %}
    <br>
    <br>

    <a href="{% url 'createcategory' %}">Add Category</a>
{% endblock %}

suggestionbox/kaizen/templates/kaizen/changestatus.html
{% extends 'base.html' %}

{% block 'title' %} New Kaizens{% endblock %}

{% block 'content' %}


    <form action="." method="post">
        {% csrf_token %}
        <table class="table">
        {{ form }}
        <td colspan="2"><button type="submit" id="submit" name="submit">Update Status</button></td>
        </table>

    </form>



{% endblock %}

suggestionbox/kaizen/templates/kaizen/comment_form.html
{% extends 'base.html' %}

{% block 'title' %} Comment on a Kaizen{% endblock %}

{% block 'content' %}

    <h1>Leave a comment:</h1>
    <form action="." method="post">
        {% csrf_token %}
        <table class="table">
        {{ form }}
        <td colspan="2"><button type="submit" id="submit" name="submit">Leave a Comment</button></td>
        </table>

    </form>



{% endblock %}

suggestionbox/kaizen/templates/kaizen/idea_detail.html
{% extends 'base.html' %}

{% block 'title' %} Kaizen Detail{% endblock %}

{% block 'content' %}

<table class="table">

        <tr>
           <td>Kaizen Title:</td><td>{{ idea.title }}</td>
        </tr>
        <tr>
            <td>Description:</td><td>{{ idea.description }}</td>
        </tr>
        <tr>
            <td>Date Published:</td><td>{{ idea.pub_date }}</td>
        </tr>
        <tr>
            <td>Status:</td><td>{{ idea.get_status_display }}</td>
        </tr>
        <tr>
            <td></td>
            <td>
                {% if request.user.is_superuser %}
                <a class="btn btn-default" href="{% url 'changestatus' idea.id %}">Change Status</a>
                {% endif %}

            </td>
        </tr>

</table>
<a href="{% url 'addcomment' idea.id %}">Leave a Comment</a>

    {% for comment in idea.comment_set.all reversed %}
        <h5> On {{ comment.pub_date|date:"M d, Y h:m" }}, {{ comment.profile.username }} said:</h5>
        <div class="well">         {{ comment.comment_text }} </div>
        {% if not forloop.last %}
        <hr>
        {% endif %}
    {% empty %}
        <p>No comments. Want to leave a <a href="{% url 'addcomment' idea.id %}">comment?</a></p>
    {% endfor %}


{% endblock %}

suggestionbox/kaizen/templates/kaizen/idea_form.html
{% extends 'base.html' %}

{% block 'title' %} New Kaizens{% endblock %}

{% block 'content' %}


    <form action="." method="post">
        {% csrf_token %}
        <table class="table">
        {{ form }}
        <td colspan="2"><button type="submit" id="submit" name="submit">Share your idea!</button></td>
        </table>

    </form>



{% endblock %}

suggestionbox/kaizen/templates/kaizen/idea_list.html
{% extends 'base.html' %}

{% block 'title' %} List of Kaizens{% endblock %}

{% block 'content' %}

    <h1>List of All User-Submitted Kaizens</h1>
    <a href="{% url 'categorylist' %}">View Category List</a>
    {% for idea in idea_list %}
        <div {% ifequal idea.profile.user request.user %} class="mark"{% endifequal %}>
        <h3>{{ idea.title }}</h3>
        <h4>Submitted by: {{ idea.profile }} on {{ idea.pub_date|date:"M d, Y h:m" }}</h4>
        <p>
            {{ idea.description }}
        </p>
        <table class="table">
            <tr>
                <td> Category </td>
                <td> {{ idea.category.title }} </td>
            </tr>
            <tr>
                <td>Status</td>
                <td>
                    {% if request.user.is_superuser %}

                            {{ idea.get_status_display }} <a href="{% url 'changestatus' idea.id %}"> (Change)
                        </a>
                    {% else %}
                        {{ idea.get_status_display }}
                    {% endif %}
                </td>
            </tr>
            <tr>

                <td colspan="2"> <a href="{% url 'ideadetail' idea.id %}">See Comments</a></td>
            </tr>

        </table>
        </div>
        <br>
        <br>
    {% empty %}
    <p>No Kaizens submitted yet. Want to <a href="">submit one?</a></p>
    {% endfor %}

    <h5>We want to hear from you!</h5><a class="btn btn-default" href="{% url 'newidea' %}">Submit your Idea</a>
{% endblock %}

suggestionbox/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block 'title' %} Kaizen{% endblock %}</title>

    <!-- Bootstrap core CSS -->

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>


    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Kaizens</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
                <!--
                 NEED TO FINISH -->
            </li>
              <li><a href="{% url 'categorylist' %}">Categories</a></li>
             <li> <a href="/accounts/signin">Sign In</a></li>
              <li>  <a href="/accounts/signout">Sign Out</a></li>
              <li> <a style="color:white;">Hello, {{ request.user }}!</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container" style="margin-top: 75px;">
{% block 'content' %}
      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
{% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </body>
</html>

suggestionbox/templates/userena/activate_retry.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}


{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block 'content' %}
<p>{% trans "Your account could not be activated because activation link is expired." %}</p>
<p><a href="{% url 'userena_activate_retry' activation_key %}">{% trans "Request a new activation link." %}</a></p>
{% endblock %}

suggestionbox/templates/userena/activate_retry_success.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}


{% block title %}{% trans "Account re-activation succeeded." %}{% endblock %}
{% block content_title %}<h2>{% trans "Account re-activation" %}</h2>{% endblock %}

{% block 'content' %}
<p>{% blocktrans %}You requested a new activation of your account..{% endblocktrans %}</p>
<p>{% blocktrans %}You have been sent an e-mail with an activation link to the supplied email.{% endblocktrans %}</p>
<p>{% blocktrans %}We will store your signup information for {{ userena_activation_days }} days on our server. {% endblocktrans %}</p>
{% endblock %}

suggestionbox/templates/userena/disabled.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Disabled account" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account has been disabled" %}</h2>{% endblock %}
{% block 'content' %}
<p>{% trans "It seems your account has been disabled." %}</p>
<p>{% trans "If you feel that injustice has been done to you, feel free to contact the administrators to find out why" %}</p>
{% endblock %} 

suggestionbox/templates/userena/email_change_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email verification" %}{% endblock %}
{% block content_title %}<h2>{% trans 'Confirm your new email' %}</h2>{% endblock %}

{% block 'content' %}
<p>{% blocktrans with viewed_user.userena_signup.email_unconfirmed as email %}You have received an email at {{ email }}.{% endblocktrans %}</p>
<p>{% blocktrans with viewed_user.username as username %}To associate this email address with your account ({{ username }}) click on the link provided in this email.{% endblocktrans %}</p>
{% endblock %}

suggestionbox/templates/userena/email_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block content_title %}<h2>{% blocktrans with user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block 'content' %}
<form action="" method="post">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last selected"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Change email address" %}</legend>
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Change email" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/password_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Password changed" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been changed" %}.</h2>{% endblock %}

{% block 'content' %}
<p>{% trans "From now on you can use your new password to signin" %}.</p>
{% endblock %}

suggestionbox/templates/userena/password_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block 'content' %}
<form action="" method="post" id="password_change_form">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li  class="selected"><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  <fieldset>
    <legend>{% trans "Change Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Change password" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/password_reset_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Password reset" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been reset" %}</h2>{% endblock %}
{% block 'content' %}
{% url 'userena_signin' as signin_url %}
{% blocktrans %}You can now <a href="{{ signin_url }}">signin</a> with your new password.{% endblocktrans %}
{% endblock %}

suggestionbox/templates/userena/password_reset_confirm_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block 'content' %}
<form action="" method="post">
  <fieldset>
    <legend>{% trans "Reset Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Reset password" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/password_reset_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block 'content' %}
<form action="" method="post">
  <fieldset>
    <legend>{% trans "Reset Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Send password" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/profile_detail.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% blocktrans with profile.user.username as username %}{{ username }}'s profile.{% endblocktrans %}{% endblock %}
{% block content_title %}<h2>{{ profile.user.username }} {% if profile.user.get_full_name %}({{ profile.user.get_full_name }}){% endif %}</h2>{% endblock %}

{% block 'content' %}
  <div class="white-box">
    {% block profile_navigation %}
      {% comment %}Dirty hack. Will use django-guardian in the future.{% endcomment %}
      {% if user.username == profile.user.username %}
        <ul id="box-nav">
          {% block profile_navigation_items %}
            <li><a href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a></li>
            <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a></li>
            <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
            <li><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}

    <div id="details">
      {% block profile_details %}
        <img class="mugshot" src="{{ profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" />
        <dl>
          {% block profile_definition_list %}
            {% if profile.user.get_full_name %}
              <dt>{% trans "Name" %}</dt>
              <dd>{{ profile.user.get_full_name }}</dd>
            {% endif %}
            {% if profile.user.email and not hide_email %}
              <dt>{% trans "Email" %}</dt>
              <dd>{{ profile.user.email }}</dd>
            {% endif %}
            {% if profile.age %}
              <dt>{% trans "Age" %}</dt>
              <dd>{{ profile.age }}</dd>
            {% endif %}
            {% if profile.website %}
              <dt>{% trans "Website" %}</dt>
              <dd>{{ profile.website|urlize }}</dd>
            {% endif %}
            {% if profile.location %}
              <dt>{% trans "Location" %}</dt>
              <dd>{{ profile.location }}</dd>
            {% endif %}
            {% if profile.about_me %}
              <dt>{% trans "About me" %}</dt>
              <dd>{{ profile.about_me }}</dd>
            {% endif %}
          {% endblock %}
        </dl>
      {% endblock %}
    </div>
  </div>
{% endblock %}

suggestionbox/templates/userena/profile_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with profile.user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block 'content' %}

<form action="" enctype="multipart/form-data" method="post">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li class="selected"><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Edit Profile" %}</legend>
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Save changes" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/profile_list.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block content_title %}<h2>{% trans 'Profiles' %}</h2>{% endblock %}

{% block 'content' %}
<ul id="profile_list">
  {% for profile in profile_list %}
  <li>
  <a href="{% url 'userena_profile_detail' profile.user.username %}"><img src="{{ profile.get_mugshot_url }}" /></a>
  <a href="{% url 'userena_profile_detail' profile.user.username %}">{{ profile.user.username }}</a>
  </li>
  {% endfor %}

</ul>

{% if is_paginated %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="{% url 'userena_profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
    {% endif %}

    <span class="current">
      {% blocktrans with page_obj.number as page and page_obj.paginator.num_pages as num_pages %}
      Page {{ page }} of {{ num_pages }}
      {% endblocktrans %}
    </span>

    {% if page_obj.has_next %}
    <a href="{% url 'userena_profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
    {% endif %}
  </span>
</div>
{% endif %}
{% endblock %}

suggestionbox/templates/userena/signin_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Signin" %}{% endblock %}

{% block 'content' %}
<form action="" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Signin" %}</legend>
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.errors }}
    {% comment %} Displaying checkboxes differently {% endcomment %}
    {% if field.name == 'remember_me' %}
    <p class="checkbox">
    <label for="id_{{ field.name }}">{{ field }} {{ field.label }}</label>
    </p>
    {% else %}
    <p>
    {{ field.label_tag }}
    {{ field }}
    </p>
    {% endif %}
    {% endfor %}
  </fieldset>
  <input type="submit" value="{% trans "Signin" %}" />
    <br></br>
  <p class="forgot-password"><a href="{% url 'userena_password_reset' %}" title="{% trans 'Forgot your password?' %}">{% trans "Forgot your password?" %}</a></p>
  <p> <a href="/accounts/signup">Sign Up</a></p>
    {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
</form>
{% endblock %}