blog/blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blogapp.urls', namespace='blogapp')), 
    url(r'^admin/', include(admin.site.urls)),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogapp/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^category/$', views.CategoryListView.as_view(), name="category"),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryDetailView.as_view(), name="categorydetail"),
    url(r'^commentsuccess/$', TemplateView.as_view(template_name='blogapp/commentsuccess.html'), name="commentsuccess"),
]

blog/blogapp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    picture = models.ImageField(upload_to="pics/%Y/%m/%d", blank=True, null=True)
    pub_date = models.DateTimeField()
    
    category = models.ManyToManyField('Category', blank=True)
    keywords = models.CharField(max_length=200, blank=True, null=True)
    
   
    def __unicode__(self):
        return self.title


class Comment(models.Model):
    person = models.CharField(max_length=200)
    comment_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post)
    #Foreign key will create a comment_set in the post class

    def __unicode__(self):
        return "%s - %s" % (self.person, self.comment_text[:50])

class Category(models.Model):
    category_name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.category_name

    class Meta: 
        verbose_name_plural = "categories"

blog/blogapp/forms.py
from django import forms

class CommentForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'size': 60}))
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 100}))
    

blog/blogapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import FormView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect

from .models import Post, Comment, Category
from .forms import CommentForm

class IndexView(generic.ListView):
    template_name = 'blogapp/index.html'
    model = Post
    

    def get_queryset(self):
        #in order to only show the most recent 5 posts:
        return Post.objects.order_by('-pub_date')[:10]

class CategoryListView(generic.ListView):
    template_name = 'blogapp/category.html'
    model = Category
    

class PostDetailView(generic.DetailView):
    model = Post
    success_url = reverse_lazy('blogapp:commentsuccess')
    
    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context["form"] = CommentForm
        return context
        
    def form_valid(self, form):
        #add a comment

        comment = Comment()
        comment.person = form.cleaned_data['name']
        comment.comment_text = form.cleaned_data['comment']
        comment.post = form.cleaned_data['post']
        comment.save()
        
        return super(PostDetailView, self).form_valid(form)

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'blogapp/categorydetail.html'

class CommentFormView(FormView):
    form_class = CommentForm
    template_name = 'blogapp/commentform.html'
    success_url = reverse_lazy('blogapp:commentsuccess')
    

    
    
    #def get_context_data(self):
        #context = super(PostDetailView,self).get_context_data()
        #context.update({"comment_list": self.get_object().comment_set.all()})
        #context.update({"comment_list": Comment.objects.filter(post__pk = self.kwargs.get('pk'))})
        #return context

blog/blogapp/templates/blogapp/_post.html
{% load thumbnail %}   
    {% if post.picture %}
        {% thumbnail post.picture "300x300" crop="center" as im %}
         <img src="{{ im.url }}" style="text-align: center;">
        {% endthumbnail %}
     {% endif %}

    <a href="{% url 'blogapp:detail' post.id %}"><h2>{{ post.title }}</h2></a><br>
    <h4><strong> 
    Published {{ post.pub_date|date:"M d, Y"}}</strong> 
    ~ Related To: 
    {% for category in post.category.all %}
        <a href="{% url 'blogapp:categorydetail' category.id %}" style="margin-right: 10px;">{{ category.category_name }} </a> 
    {% empty %}
        None.
    {% endfor %}
    
    </h4>
    <div class="post-body">
    <pre style="background-color:white; border: 0px; font-family:arial, sans-serif;">{{ post.body }}</pre>
    </div>
    

blog/blogapp/templates/blogapp/category.html
{% extends 'base.html' %}
{% block 'title' %}Carita's Blog Categories{% endblock 'title' %}

{% block 'content' %}

<h2> Blog Post Categories </h2>
<hr>
{% if category_list %}
  
  {% for category in category_list %}

     <a href="{% url 'blogapp:categorydetail' category.id %}"> {{ category.category_name }} </a> 
     <br>
  {% endfor %}
  
{% else %}

<p> No categories to show. </p>

{% endif %}
<hr>
{% endblock 'content' %}

blog/blogapp/templates/blogapp/categorydetail.html
{% extends 'base.html' %}

{% block 'title' %}{{ category.category_name }} Blog Posts{% endblock 'title' %}

{% block 'content' %}
    {% for post in category.post_set.all %}
        {% include 'blogapp/_post.html' %}  
        <br>
        <hr>
    {% endfor %}
    


{% endblock 'content' %}

blog/blogapp/templates/blogapp/commentsuccess.html
{% extends 'base.html' %}
{% block 'title' %}Thanks for your comment{% endblock 'title' %}

{% block 'content' %}

    <h1> Thank you for your comment! </h2>


{% endblock 'content' %}

blog/blogapp/templates/blogapp/index.html
{% extends 'base.html' %}
{% block 'title' %}Carita's Most Recent Blog Posts{% endblock 'title' %}

{% block 'content' %}

<h1> Most Recent Blog Posts </h2>

{% if post_list %}
  
  {% for post in post_list %}

    {% include 'blogapp/_post.html' %}
    <br>
    <a href="{% url 'blogapp:detail' post.id %}#comment-section">Leave a comment...</a>
    <br>
    
        {% if not foorloop.last %}
        <hr>
        {% endif %}
        
  {% endfor %}

{% else %}

<p> No posts to show. </p>

{% endif %}

{% endblock 'content' %}

blog/blogapp/templates/blogapp/post_detail.html
{% extends 'base.html' %}

{% block 'title' %}{{ post.title }} {% endblock 'title' %}

{% block 'content' %}

    {% include 'blogapp/_post.html' %}
    
    
    <br><br>
    <div id="comment-section"> <!-- begin comment section -->
    
    <h4> Leave a Comment</h4>
    <form action="{% url 'blogapp:commentsuccess' %}" method='post'>
    {% csrf_token %}
    <input type="hidden" id="post" name="post" value="{{ post.id }}">
    <table class="table">
    {{ form }}

    <tr>
        <td colspan="2"><input type="submit" value="Submit Comment"></td>
    </tr>
    </table>

    </form>
    
    
    <br><br>
    {% for comment in post.comment_set.all reversed %}
    
        <h5> On {{ comment.pub_date|date:"M d, Y h:m" }}, {{ comment.person }} said: </h5>
        <div class="well"> {{ comment.comment_text }} </div>
        
        {% if not forloop.last %}
        <hr>
        {% endif %}
        
        
    {% empty %}
        <p> Be the first to comment on this post. </p>
        
    {% endfor %}
    </div> <!-- end comment-section -->

{% endblock 'content' %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block 'title' %} Sticky Footer Navbar Template for Bootstrap {% endblock %}</title>
    <!-- Bootstrap core CSS -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Carita's Blog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/category">Topics</a></li>
            <li><a href="/admin">Admin</a></li>
            
            <li><a href="mailto:carita.guarda@dmail.dixie.edu">Contact</a></li>
            <!--<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->
    <div class="container" style="margin-top: 50px;">
    {% block 'content' %}
      <div class="page-header">
        <h1>Sticky footer with fixed navbar</h1>
      </div>
      <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code>padding-top: 60px;</code> on the <code>body > .container</code>.</p>
      <p>Back to <a href="../sticky-footer">the default sticky footer</a> minus the navbar.</p>
   {% endblock %}
    </div>

    
    <footer class="footer">
      <div class="container">
        <p class="text-muted"> &copy; Carita Guarda 2015</p>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

blog/templates/baseold.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block 'title' %} Starter Template for Bootstrap {% endblock %}</title>

    <!-- Bootstrap core CSS -->

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Home</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/admin">Admin</a></li>
            <li><a href="mailto:D00079614@dmail.dixie.edu">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container" style="margin-top: 75px;">
{% block 'content' %}
      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
{% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>