crminal/crm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from viewsets import ModelViewSet

from views import *


urlpatterns = [
    url(r'^$', login_required(DashboardView.as_view()), name="dashboard"),

    url(r'^call/all/$', login_required(CallListView.as_view()), name="calllist" ),
    url(r'^call/(?P<pk>\d+)/$', login_required(CallDetailView.as_view()), name="calldetail"),
    url(r'^call/(?P<pk>\d+)/edit/$', login_required(CallEditView.as_view()), name="calledit"),
    url(r'^call/add/(?P<pk>\d+)/$', login_required(CallAddView.as_view()), name="calladd"),
    url(r'^call/(?P<pk>\d+)/delete/$', login_required(CallDeleteView.as_view()), name="calldelete"),

    url(r'^search/$', login_required(SearchResultsView.as_view()), name="search"),

    url(r'^opportunity/all/$', login_required(OpportunityListView.as_view()), name="opportunitylist" ),
    url(r'^opportunity/add/$', login_required(OpportunityAddView.as_view()), name="opportunityadd"),
    url(r'^opportunity/(?P<pk>\d+)/$', login_required(OpportunityDetailView.as_view()), name="opportunitydetail"),
    url(r'^opportunity/(?P<pk>\d+)/edit/$', login_required(OpportunityEditView.as_view()), name="opportunityedit"),
    url(r'^opportunity/(?P<pk>\d+)/delete/$', login_required(OpportunityDeleteView.as_view()), name="opportunitydelete"),
    url(r'^opportunity/(?P<pk>\d+)/reminder/$', login_required(AddOpportunityReminderView.as_view()), name="opportunityreminder"),


    url(r'^contact/all/$', login_required(ContactListView.as_view()), name="contactlist" ),
    url(r'^contact/add/$', login_required(ContactAddView.as_view()), name="contactadd"),
    url(r'^contact/(?P<pk>\d+)/$', login_required(ContactDetailView.as_view()), name="contactdetail"),
    url(r'^contact/(?P<pk>\d+)/edit/$', login_required(ContactEditView.as_view()), name="contactedit"),
    url(r'^contact/(?P<pk>\d+)/delete/$', login_required(ContactDeleteView.as_view()), name="contactdelete"),
    
    url(r'^company/all/$', login_required(CompanyListView.as_view()), name="companylist" ),
    url(r'^company/add/$', login_required(CompanyAddView.as_view()), name="companyadd"),
    url(r'^company/(?P<pk>\d+)/$', login_required(CompanyDetailView.as_view()), name="companydetail"),
    url(r'^company/(?P<pk>\d+)/edit/$', login_required(CompanyEditView.as_view()), name="companyedit"),
    url(r'^company/(?P<pk>\d+)/delete/$', login_required(CompanyDeleteView.as_view()), name="companydelete"),
    
    url(r'^reports/$', login_required(ReportListView.as_view()), name="reports" ),
    
    url(r'^reminder/all/$', login_required(ReminderListView.as_view()), name="reminderlist" ),
    url(r'^reminder/add/$', login_required(ReminderAddView.as_view()), name="reminderadd"),
    url(r'^reminder/(?P<pk>\d+)/edit/$', login_required(ReminderEditView.as_view()), name="reminderedit"),
    url(r'^reminder/(?P<pk>\d+)/delete/$', login_required(ReminderDeleteView.as_view()), name="reminderdelete"),
    url(r'^reminder/complete/$', login_required(ReminderCompleteView.as_view()), name="remindercomplete"),


    url(r'^stage/all/$', login_required(StageListView.as_view()), name="stagelist" ),
    url(r'^stage/(?P<pk>\d+)/edit/$', login_required(StageEditView.as_view()), name="stageedit"),
    url(r'^stage/(?P<pk>\d+)/$', login_required(StageDetailView.as_view()), name="stagedetail"),


    url(r'^campaign/all/$', login_required(CampaignListView.as_view()), name="campaignlist" ),
    url(r'^campaign/add/$', login_required(CampaignAddView.as_view()), name="campaignadd"),
    url(r'^campaign/(?P<pk>\d+)/$', login_required(CampaignDetailView.as_view()), name="campaigndetail"),
    url(r'^campaign/(?P<pk>\d+)/edit/$', login_required(CampaignEditView.as_view()), name="campaignedit"),


]

crminal/crminal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('crm.urls', namespace='crm')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crminal/crm/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


# Create your models here.
class Stage(models.Model):
    name = models.CharField(max_length=200)
    order = models.IntegerField(help_text= "The order this is displayed on the screen")
    value = models.IntegerField(help_text="On a scale of 0 to 100 of the stage of the pipeline")
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['order']


class Company(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField(max_length=200, blank=True, null=True)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=200, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def getAddress(self):
        address = ""
        if self.address1:
            address += self.address1
            address += ","
        if self.address2:
            address += self.address2
            address += ", "
        if self.city:
            address += self.city
            address += ", "
        if self.state:
            address += self.state
            address += ","
        if self.zipcode:
            address += self.zipcode
        if address != "":
            return address
        else:
            return None


    class Meta:
        verbose_name_plural = 'companies'


class Contact(models.Model):
    company = models.ForeignKey(Company, blank=True, null=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True)

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def getAddress(self):
        address = ""
        if self.address1:
            address += self.address1
            address += ","
        if self.address2:
            address += self.address2
            address += ", "
        if self.city:
            address += self.city
            address += ", "
        if self.state:
            address += self.state
            address += ","
        if self.zipcode:
            address += self.zipcode
        if address != "":
            return address
        else:
            return None

    def __unicode__(self):
        return self.get_full_name()



class Campaign(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    def get_opportunity_count(self):
        opportunity_list = []
        for opportunity in Opportunity.objects.all().filter(source = self.id):
            opportunity_list.append(opportunity)
        return len(opportunity_list)



class Opportunity(models.Model):
    description = models.CharField(max_length=200, blank=True, null=True)
    stage = models.ForeignKey(Stage)
    company = models.ForeignKey(Company, blank=True, null=True)
    contact = models.ForeignKey(Contact)
    value = models.FloatField(help_text="How much this opportunity is worth to the organization")
    source = models.ForeignKey(Campaign)
    user = models.ForeignKey(User)
    create_date = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'opportunities'

    def __unicode__(self):
        if self.company and self.contact:
            return str(self.contact) + " @ " + str(self.company)
        elif self.company:
            return str(self.company)
        else:
            return str(self.contact)



class Reminder(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    date = models.DateTimeField()
    note = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __unicode__(self):
        str(self.opportunity) + ": " + self.note

    def markComplete(self):
        self.complete = True

class Report(models.Model):
    name = models.CharField(max_length=200)
    link = models.URLField()

    def __unicode__(self):
        return self.name


class CallLog(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    date = models.DateTimeField(default=datetime.datetime.now)
    note = models.TextField()
    user = models.ForeignKey(User)

    def __unicode__(self):
        return str(self.opportunity) + " on " + self.date.strftime("%Y-%m-%d") + " on " + self.user.get_full_name()


class OpportunityStage(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    stage = models.ForeignKey(Stage)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return str(self.opportunity) + " moved to " + str(self.stage)

crminal/crm/forms.py
from django import forms

class CreateOpportunityForm(forms.Form):
    contact = forms.ModelForm(queryset='Contact')
    company = forms.ModelForm(queryset='Company', empty_label="None")
    stage = forms.ModelForm(queryset='Stage')
    value = forms.IntegerField()
    source = forms.ModelForm(queryset='Campaign')

crminal/crm/templates/crm/calllog_edit.html
{% extends 'base.html' %}
{% block title %}Update A Call{% endblock %}
{% block content %}
<h1>Update A Call</h1>

<form action="." method="post">
{% csrf_token %}
<table class="table">
{{ form }}


</table>

<input type="submit" value="Update"/>
<a href="{% url 'crm:calldelete' calllog.id %}">Delete</a>
</form>
<br>


{% endblock %}

crminal/crm/templates/crm/calllog_list.html
{% extends 'base.html' %}

{% block title %} Call List {% endblock %}

{% block content %}


    <table class="table">
        <tr>
            <th> User </th>

            <th> Opportunity </th>
            <th> Date </th>
            <th> </th>

        </tr>
         {% for call in calllog_list %}
         <tr>
             <td> {{ call.user }} </td>
             <td> {{ call.opportunity }}</td>
             <td> {{ call.date }}</td>
             <td> <a href="{% url 'crm:calldetail' call.id %}"> View Call</a></td>
         </tr>
         {%  empty %}
             <tr> No calls saved.</tr>
         {% endfor %}

    </table>

    <button><a href="{% url 'crm:calladd' %}">Add a Call</a></button>

{% endblock %}

crminal/crm/templates/crm/campaign_detail.html
{% extends 'base.html' %}

{% block title %} Campaign Detail {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <h1>Campaign Details</h1>
            <table class="table">
                <tr>
                    <th> Name:</th>
                    <td> {{ campaign.name }}</td>
                </tr>

                <tr>
                    <th> Description:</th>
                    <td> {{ campaign.description }} </td>
                </tr>
                <tr>
                    <th> Opportunites Generated:</th>
                    <td>
                        {% for opportunity in opportunity_list %}
                            <a href="{% url 'crm:opportunitydetail' opportunity.id %}">{{ opportunity }}</a> <br>
                        {% endfor %}

                    </td>
                </tr>
               <tr>
                   <td></td>
                   <th class="text-center"> Total: {{ campaign.get_opportunity_count }} </th>
               </tr>
            </table>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-2"><a href="{% url 'crm:campaignedit' campaign.id %}"><button class="btn">Edit</button></a></div>
        <div class="col-lg-2"></div>
        <div class="col-lg-2"><a class="pull-right" href="{% url 'crm:campaignlist' %}"><button class="btn">Back</button></a></div>
        <div class="col-lg-3"></div>
    </div>




{% endblock %}

crminal/crm/templates/crm/contact_detail.html
{% extends 'base.html' %}

{% block title %} Contact Detail {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <table class="table">
                <tr>
                    <th> Contact Name:</th>
                    <td> {{ contact.first_name }} {{ contact.last_name }} </td>
                </tr>

                <tr>
                    <th> Company:</th>
                    <td> {{ contact.company }} </td>
                </tr>

               <tr>
                    <th> Phone:</th>
                    <td> {{ contact.phone }} </td>
                </tr>

                <tr>
                    <th> Email:</th>
                    <td> {{ contact.email }} </td>
                </tr>

                <tr>
                    <th> Address:</th>
                    <td>
                        {{ contact.address1 }}<br>
                        {% if contact.address2 %}
                        {{ contact.address2 }}<br>
                        {% endif %}
                        {{ contact.city }} {{ contact.state }} {{ contact.zipcode }}<br>
                        {% if contact.country %}
                        {{ contact.country }} <br>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Opportunities:</th>
                    <td>
                        {% for opportunity in opportunity_list %}

                            <a class="text-right" href="{% url 'crm:opportunitydetail' opportunity.id %}">
                                {% if opportunity.description %}{{ opportunity.description }} {% else %} {{ opportunity }} {% endif %} <br>
                            </a>

                        {% endfor %}
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-2"><a href="{% url 'crm:contactedit' contact.id %}"><button class="btn">Edit</button></a></div>
        <div class="col-lg-2"><a href="{% url 'crm:contactdelete' contact.id %}"><button class="btn">Delete</button></a></div>
        <div class="col-lg-2"><a href="{% url 'crm:contactlist' %}"><button class="btn">Back</button></a></div>
        <div class="col-lg-3"></div>
    </div>




{% endblock %}

crminal/crm/templates/crm/contact_form.html
{% extends 'base.html' %}

{% block title %}{% if contact %}Update{% else %}Add{% endif %} A Contact{% endblock %}

{% block content %}

      <div class = "row">
        <div class = "col-lg-3"></div>
        <div class = "col-lg-3">
        <h1> {% if contact %}Update{% else %}Add{% endif %} Contact</h1>
        </div>

        <div class = "col-lg-3" style = "padding-left: 13.5em; padding-top: 1em;" >
           {% if contact %}
                <a href="{% url 'crm:contactdetail' contact.id %}"><button  class="btn">Cancel</button></a>
            {% else %}
                <a href="{% url 'crm:contactlist' %}"><button class="btn">Cancel</button></a>
            {% endif %}
        </div>
        <div class = "col-lg-3"></div>

    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form action="." method="post">
            {% csrf_token %}

            <table class="table">
            {{ form }}


            </table>

            <input class="btn pull-right" type="submit" value="{% if contact %}Update{% else %}Add{% endif %}"/>

            </form>
            {% if contact %}
                <a href="{% url 'crm:contactdelete' contact.id %}"><button class="btn">Delete</button></a>
            {% endif %}
        </div>

        <div class="col-lg-3">
        </div>
    </div>


    <br>


{% endblock %}

crminal/crm/templates/crm/contact_list.html
{% extends 'base.html' %}

{% block title %} Contact List {% endblock %}

{% block content %}
    <div class = "row">
        <div class = "col-lg-6">
        <h1> Contact List</h1>
        </div>
        <div class = "col-lg-3"></div>
        <div class = "col-lg-3 pull-right">
        <a href="{% url 'crm:contactadd' %}"><button style = "margin-top: 30px;" class="btn">Add a Contact</button></a>
        </div>
    </div>
    <table class="table">
        <tr>
            <th> Contact </th>

            <th> Company </th>
            <th> Phone </th>
            <th> Email </th>
            <th> </th>

        </tr>
         {% for contact in contact_list %}
         <tr>
             <td> {{ contact.first_name }} {{ contact.last_name }} </td>
             <td> {{ contact.company }}</td>
             <td> {{ contact.phone }}</td>
              <td> {{ contact.email }}</td>

             <td> <a href="{% url 'crm:contactdetail' contact.id %}" style="color:gray"> View Details</a></td>

         </tr>
         {%  empty %}
             <tr> <td colspan="5"> No contacts saved.</td> </tr>
         {% endfor %}

    </table>


{% endblock %}

crminal/crm/templates/crm/opportunity_detail.html
{% extends 'base.html' %}
{% block title %}Opportunity Dashboard{% endblock %}
{% block extrascripts %}

{% endblock %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-lg-12">
            <h1 style="margin-top: 10px;">{{ opportunity }} </h1>
            <h2> {{ opportunity.description }} (Stage: {{ opportunity.stage }})<a class="btn btn-primary btn-fab btn-raised mdi-content-create pull-right" href="{% url 'crm:opportunityedit' opportunity.id %}" title="Edit Opportunity"></a></h2>
        </div>
    </div>
</div>

    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Contact Information
                    <span class="text-right pull-right">
                            <a href="{% url 'crm:contactedit' opportunity.contact.id %}" class="btn btn-primary btn-sm mdi-content-create" style="margin-top: -7px;" title="Edit Contact"></a>
                    </span>
                </div>
                <div class="panel-body">
                <br>
                <table class="table">
                    <tr>
                        <td>Company</td>
                        <td>
                            {% if opportunity.company %}
                            <a href="{% url 'crm:companydetail' opportunity.company.id %}">{{ opportunity.company }}</a>
                            {% else %}
                            None
                            {% endif %}
                        </td>
                    </tr>
                    {% if opportunity.contact.getAddress %}
                    <tr>
                        <td>Address</td>
                        <td>{{ opportunity.contact.address1 }}<br>
                            {% if opportunity.contact.address2 %}
                            {{ opportunity.contact.address2 }}<br>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>City</td>
                        <td>{{ opportunity.contact.city }} </td>
                    </tr>
                    <tr>
                        <td>State, Zip</td>
                        <td>
                            {{ opportunity.contact.state }} {{ opportunity.contact.zipcode }}
                        </td>
                    </tr>
                    {% if opportunity.contact.country %}
                    <tr>
                        <td>Country</td>
                         <td>{{ opportunity.contact.country }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td>Phone</td>
                        <td>{{ opportunity.contact.phone }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><a href="mailto:{{ opportunity.contact.email }}">{{ opportunity.contact.email }}</a></td>
                    </tr>
                    {% else %}
                    <tr>
                        <td>Address</td>
                        <td>{{ opportunity.company.address1 }}<br>
                            {% if opportunity.company.address2 %}
                            {{ opportunity.company.address2 }}<br>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>City</td>
                        <td>{{ opportunity.company.city }} </td>
                    </tr>
                    <tr>
                        <td>State, Zip</td>
                        <td>
                            {{ opportunity.company.state }} {{ opportunity.company.zipcode }}
                        </td>
                    </tr>
                    {% if opportunity.company.country %}
                    <tr>
                        <td>Country</td>
                         <td>{{ opportunity.company.country }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td>Phone</td>
                        <td>{{ opportunity.company.phone }}</td>
                    </tr>
                    <tr>
                        <td>Website</td>
                        <td><a href="mailto:{{ opportunity.company.website }}">{{ opportunity.company.website }}</a></td>
                    </tr>
                    {% endif %}
                </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Map
                        <span class="text-right pull-right">
                            <a href="{% url 'crm:contactedit' opportunity.contact.id %}" class="btn btn-primary btn-sm mdi-action-list" style="margin-top: -7px;" title="Update Address"></a>
                        </span>
                </div>
                <div class="panel-body">

    <center><div id="map" style="width: auto; height: 300px;"></div></center>
<script>
var map;
function initMap() {
    address = '{% if opportunity.contact.getAddress %} {{ opportunity.contact.getAddress }} {% elif opportunity.company.getAddress %} {{ opportunity.company.getAddress }} {% endif %}';
    var geocoder  = new google.maps.Geocoder();
    geocoder.geocode({ 'address': address}, function(results, status) {
        var c = results[0].geometry.location;
        latitude  = c.lat();
        longitude = c.lng();
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: latitude, lng: longitude},
            scrollwheel: false,
            zoom: 14,
        });
        var marker = new google.maps.Marker({
            map: map,
            position: {lat: latitude, lng: longitude},
            title: 'Opportunity Name',
        });
    });
}
</script>
<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyDxCDEfKuCyTVE-Ex43CG5PQec_Uc5CiQQ&callback=initMap" async defer></script>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Call Log
                        <span class="text-right pull-right">
                            <a href="{% url 'crm:calladd' opportunity.id %}" class="btn btn-primary btn-sm mdi-content-add-box" style="margin-top: -7px;" title="Add Call"></a>
                        </span>
                </div>
                <div class="panel-body">
                <br>
                <table class="table">
                <tr>
                    <th>Date</th>
                    <th>Note</th>
                    <th>By</th>
                </tr>
                {% for call in recent_calls %}
                <tr>
                    <td>{{ call.date }}</td>
                    <td>{{ call.note }}</td>
                    <td>{{ call.user }}</td>
                </tr>
                {% endfor %}
                </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Stage History
                        <!-- class="text-right pull-right">
                            <a href="" class="btn btn-primary btn-sm mdi-content-create" style="margin-top: -7px;" title="Change Stage"></a>
                        </ -->
                </div>
                <div class="panel-body">
                    <br>
                    <table class="table">
                    <tr>
                        <th>Date</th>
                        <th>Stage</th>
                        <th>User</th>
                    </tr>
                    {% for oppportunitystage in opportunity.opportunitystage_set.all %}
                    <tr>
                        <td>{{  oppportunitystage.timestamp }}</td>
                        <td>{{ oppportunitystage.stage }}</td>
                        <td>{{ oppportunitystage.user }}</td>
                    </tr>
                    {% endfor %}

                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Reminders
                    <span class="text-right pull-right">
                            <a href="{% url 'crm:opportunityreminder' opportunity.id %}" class="btn btn-primary btn-sm mdi-content-create" style="margin-top: -7px;" title="Add Reminder"></a>
                    </span>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <th> Date </th>
                            <th> Note </th>
                            <th> Completed?</th>
                            <th> </th>
                        </tr>
                        {% for reminder in opportunity.reminder_set.all %}
                            <tr>
                                <td> {{ reminder.date }} </td>
                                <td> {{ reminder.note }}</td>
                                <td>
                                    {% if reminder.completed %}
                                    Yes
                                    {% else %}
                                    No
                                    {% endif %}
                                </td>
                                <td> <a href="{% url 'crm:reminderedit' reminder.id %}"> Edit</a> </td>
                            </tr>
                        {% empty %}
                        <tr> <td colspan="3"> No Reminders Found for this Opportunity </td></tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

crminal/crm/templates/crm/opportunity_list.html
{% extends 'base.html' %}

{% block title %} Opportunity List {% endblock %}

{% block content %}
    <div class = "row">
        <div class = "col-lg-6">
        <h1> All Opportunities </h1>
        </div>
        <div class = "col-lg-3"></div>
        <div class = "col-lg-3 pull-right">
        <a href="{% url 'crm:opportunityadd' %}"><button style = "margin-top: 30px;" class="btn">Add an Opportunity</button></a>
        </div>
    </div>
    <table class="table">
        <tr>
            <th> Contact </th>
            <th> Company </th>
            <th> Description </th>

            <th></th>

        </tr>
         {% for opportunity in opportunity_list %}
         <tr>
             <td> {{ opportunity.contact.get_full_name }} </td>
             <td> {{ opportunity.company }}</td>
             <td> {{ opportunity.description }}</td>
             <td> <a href="{% url 'crm:opportunitydetail' opportunity.id %}" style="color:gray"> View Details</a></td>

         </tr>
         {%  empty %}
             <tr> <td colspan="4"> No opportunities saved.</td> </tr>
         {% endfor %}

    </table>


{% endblock %}

crminal/crm/templates/crm/reminder_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete A Reminder{% endblock %}
{% block content %}

        <div class = "row">
        <div class = "col-lg-9">
       <h1>Are you sure you want to delete this Reminder?</h1>
        </div>
        <div class = "col-lg-3 pull-right">
        <a href="{% url 'crm:remindercomplete' %}"><button style = "margin-top: 30px;" class="btn">Cancel</button></a>
        </div>
        </div>


<p>This action cannot be undone.</p>
<form action="." method="post">
{% csrf_token %}
{{ form }}



<input class="btn" type="submit" value="Delete"/>
</form>
<br>


{% endblock %}

crminal/crm/templates/crm/stage_detail.html
{% extends 'base.html' %}

{% block title %} Stage Detail {% endblock %}

{% block content %}
    <h1> Opportunities by Stage: {{ stage.name }}</h1>

    <table class="table">
        <tr>
            <th> Opportunity </th>

            <th> Description </th>
            <th> Value </th>
            <th></th>
        </tr>
        {% for opportunity in stage.opportunity_set.all %}
         <tr>
             <td> {{ opportunity }} </td>
             <td> {{ opportunity.description }}</td>
             <td> {{ opportunity.value }}</td>
             <td><a href="{% url 'crm:opportunitydetail' opportunity.id %}">View</a></td>
         </tr>
        {% empty %}
        <tr>
            <td colspan="4"> No opportunities found in this stage. </td>
        </tr>
        {% endfor %}

    </table>

{% endblock %}

crminal/crm/templates/crm/stage_list.html
{% extends 'base.html' %}

{% block title %} Stage List {% endblock %}

{% block content %}
    <h1>Stages</h1>
    <div row>
        <table class="table">
            <tr>
                <th> Name </th>
                <th>Opportunities</th>

            </tr>
             {% for stage in stage_list %}
             <tr>
                 <td> {{ stage.name }} </td>
                 <td> <a href="{% url 'crm:stagedetail' stage.id %}"> View</a></td>
             </tr>
             {% endfor %}

        </table>
    </div>

{% endblock %}